# Generated by Django 3.1.6 on 2021-02-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210116_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
