# Generated by Django 3.1.7 on 2021-02-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_noticia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
