# Generated by Django 3.2.5 on 2021-07-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210223_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='media_url',
        ),
    ]
