# Generated by Django 3.1.2 on 2020-11-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0002_auto_20201103_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla',
            options={'ordering': ('puntos',)},
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competiciones.equipo')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
