# Generated by Django 3.1.2 on 2020-11-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0003_auto_20201103_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competiciones.competicion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competiciones.jugador')),
            ],
            options={
                'ordering': ('goles',),
            },
        ),
    ]
