# Generated by Django 3.1.2 on 2020-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0005_ranking_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='puntos_por_empate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='puntos_por_ganados',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
